name: "file-service-builder"
run-name: "File service builder"
on:
  push:
    branches:
      - main
    paths:
      - file-service/**
jobs:
  build-file-service:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        name: "Checkout repository"
        with:
          sparse-checkout: file-service

      - uses: VaultVulp/gp-docker-action@1.6.0
        name: "Build and upload Docker image"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: file-service
          build-context: file-service
